### ISSUE TITLE
answer my request

### ISSUE THREAD

**Issue by OwnerSCIFahrul** [DaMatrix/NukkitPlugins#1]
please build jar plugin floatingparticles, i need plugin you..

**Comment by DaMatrix** [comment]
i'll update it after i finish working on nukkit 2.0, as the api is still not quite stable and things will change. for now, even if i build it it won't run.

**Comment by DaMatrix** [comment]
also, you could consider building it yourself... it's not that difficult...

**Comment by OwnerSCIFahrul** [comment]
oh no, I'm not a plugin developer, so I'm just asking you, if it's not
working right now, I'm waiting for me ..

Pada tanggal Sab, 25 Jan 2020 19.56 DaPorkchop_ <notifications@github.com
menulis:
